spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client_files
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /static/**